---
version: "2"
services:
    www:
        build: .
        environment:
        - IMAGE_NAME=muhammadusama7/phpcicd
        ports:
            - "80:80"
#         volumes:
#             - ./www:/var/www/html/
        networks:
            - default
        command: sh -c 'TAG=$(date +%Y%m%d%H%M%S) && docker tag $IMAGE_NAME:$TAG && docker push $IMAGE_NAME:$TAG && /usr/sbin/apache2ctl -D FOREGROUND'

