name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#     - name: Set up Minikube
#       run: |
#         sudo minikube config set driver none
#         sudo minikube start

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: muhammadusama7/phpcicd:latest

#     - name: Set up kubectl
#       run: |
#         sudo mv ~/.kube $HOME/.kube
#         sudo chown -R $USER $HOME/.kube
#         sudo chgrp -R $USER $HOME/.kube
#         echo "$HOME/.kube/config"

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
